name: Update Medium Posts

on:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam
  workflow_dispatch:  # Memungkinkan Anda untuk menjalankannya secara manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Fetch Medium Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@ikhsan.budi.wicaksono"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Updated Medium posts" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
