name: Update README with Medium Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada tengah malam
  workflow_dispatch:  # Memungkinkan menjalankan manual

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Fetch latest Medium posts
      run: |
        python scripts/fetch_medium_posts.py

    - name: Update README
      run: |
        python scripts/update_readme.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
