name: Update Medium Posts

on:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap jam
  workflow_dispatch:  # Memungkinkan Anda untuk menjalankannya secara manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@@ikhsan.budi.wicaksono"
